#!/usr/bin/env python3
"""Copy the shared prompt partials into the consumer checkouts.

The partials in this repo (partials/*.md) are the single source of truth for
prompt blocks both apps embed via an `{{ include <name> }}` directive (TODO
1.4 "Shared prompt partials library" in my-dev-team/TODO.md). This script
copies them, with a GENERATED marker prepended to the frontmatter, into:

  my-dev-team          src/devteam/config/agents/partials/<name>.md
  my-dev-team-vs-code  src/engine/config/partials/<name>.md

Both loaders read the same format (YAML frontmatter with a `name`, markdown
body = the block), so the copies are byte-identical. Hand-written app-local
partials live in the same target directories; the sync only ever touches
files carrying its GENERATED marker - it overwrites the shared ones and
deletes stale generated files whose source partial was removed, and never
touches a file without the marker.

Validation: a partial's `name` must match its file stem, and the body must
not contain stray `{` or `}` outside include directives - my-dev-team feeds
the resolved prompt to a LangChain template where a stray brace is parsed as
a template variable.

Usage, from anywhere (paths default to sibling checkouts of this repo):

  python scripts/sync_partials.py [--devteam PATH] [--vscode PATH] [--check]

--check writes nothing: it reports files that would change and exits 1 on
drift, so it can guard CI or a pre-commit hook.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from sync_models import sync_file

REPO_ROOT = Path(__file__).resolve().parent.parent

GENERATED_NOTE = 'GENERATED by my-dev-team-config/scripts/sync_partials.py - edit partials/{name}.md there, not this file.'

INCLUDE_DIRECTIVE = re.compile(r'\{\{\s*include\s+[\w./-]+?(?:\s+if\s+(?:not\s+)?\w+)?\s*\}\}')


def fail(message: str) -> None:
    raise SystemExit(f'partials invalid: {message}')


def load_partials(directory: Path) -> dict[str, str]:
    """Parse partials/*.md into {name: generated file content}."""
    generated: dict[str, str] = {}
    files = sorted(directory.glob('*.md'))
    if not files:
        fail(f'no partials found in {directory}')
    for path in files:
        text = path.read_text(encoding='utf-8')
        parts = text.split('---', 2)
        if len(parts) < 3:
            fail(f'{path.name}: missing YAML frontmatter')
        frontmatter, body = parts[1], parts[2].strip()
        name_match = re.search(r'^name:\s*(\S+)\s*$', frontmatter, re.MULTILINE)
        if not name_match or name_match.group(1) != path.stem:
            fail(f'{path.name}: frontmatter name must be {path.stem!r}')
        if not re.search(r'^description:\s*\S', frontmatter, re.MULTILINE):
            fail(f'{path.name}: missing description')
        if not body:
            fail(f'{path.name}: empty body')
        if re.search(r'[{}]', INCLUDE_DIRECTIVE.sub('', body)):
            fail(f'{path.name}: stray brace in body - braces break LangChain prompt templates')
        note = GENERATED_NOTE.format(name=path.stem)
        generated[path.stem] = f'---\n# {note}\n{frontmatter.strip()}\n---\n\n{body}\n'
    return generated


def sync_dir(target_dir: Path, generated: dict[str, str], check: bool) -> bool:
    """Write the generated partials into target_dir; prune stale generated files."""
    drift = False
    for name, content in generated.items():
        path = target_dir / f'{name}.md'
        state = sync_file(path, content, check)
        drift |= state != 'unchanged'
        print(f'{state:>9}  {path}')
    for stale in sorted(target_dir.glob('*.md')):
        if stale.stem in generated:
            continue
        if 'GENERATED by my-dev-team-config/scripts/sync_partials.py' not in stale.read_text(encoding='utf-8'):
            continue  # a hand-written app-local partial - never ours to touch
        drift = True
        if not check:
            stale.unlink()
        print(f'{"deleted":>9}  {stale}')
    return drift


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--devteam', type=Path, default=REPO_ROOT.parent / 'my-dev-team',
                        help='path to the my-dev-team checkout (default: sibling)')
    parser.add_argument('--vscode', type=Path, default=REPO_ROOT.parent / 'my-dev-team-vs-code',
                        help='path to the my-dev-team-vs-code checkout (default: sibling)')
    parser.add_argument('--check', action='store_true',
                        help='write nothing; exit 1 when a generated file would change')
    args = parser.parse_args()

    generated = load_partials(REPO_ROOT / 'partials')
    drift = False
    drift |= sync_dir(args.devteam / 'src' / 'devteam' / 'config' / 'agents' / 'partials', generated, args.check)
    drift |= sync_dir(args.vscode / 'src' / 'engine' / 'config' / 'partials', generated, args.check)

    if args.check and drift:
        print('\ndrift detected: run python scripts/sync_partials.py to regenerate')
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
