#!/usr/bin/env python3
"""Generate the app-native model registries from the shared models.yaml.

The shared registry (models.yaml, in this repo) is the single source of truth
for every model the two apps may route to. This script translates it into each
app's native dialect and writes the result into the sibling checkouts:

  my-dev-team          src/devteam/config/tools/llms.yaml   (one YAML catalogue)
  my-dev-team-vs-code  src/engine/config/models/*.md        (one .md per model)

Dialect translation rules:

  - capabilities: the registry uses the unified 8-name vocabulary and both
    apps receive it verbatim (my-dev-team's router scores any name
    generically; vs-code's enum speaks the unified names since 0.79.0, with
    the old `coding`/`speed` dialect accepted as aliases for hand-written
    config).
  - complexity: the registry's complexity_fit multipliers go to my-dev-team
    verbatim; vs-code's `tier` is derived as the argmax of complexity_fit
    (low=simple, medium=moderate, high=complex), which the validator requires
    to be unique.
  - providers: each app only receives models on providers it can instantiate
    (see the two lists below). An entry's `also_via` providers additionally
    place a copy in those llms.yaml sections (the Azure mirrors).
  - compound providers (`free`) and `aliases` exist only in llms.yaml.

Usage, from anywhere (paths default to sibling checkouts of this repo):

  python scripts/sync_models.py [--devteam PATH] [--vscode PATH] [--check]

--check writes nothing: it reports files that would change and exits 1 on
drift, so it can guard CI or a pre-commit hook.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent

# The unified capability vocabulary (TODO 1.2), also the emission order.
UNIFIED_CAPABILITIES = [
    'reasoning',
    'code-generation',
    'code-analysis',
    'classification',
    'planning',
    'fast-utility',
    'structured-output',
    'long-context',
]

COMPLEXITY_LEVELS = ['low', 'medium', 'high']
TIER_BY_LEVEL = {'low': 'simple', 'medium': 'moderate', 'high': 'complex'}

# Providers each app can instantiate today. Keep in sync with
# my-dev-team's LLMFactory._instantiate() and vs-code's config/providers.ts.
DEVTEAM_PROVIDERS = [
    'groq', 'ollama', 'anthropic', 'openai', 'grok', 'google', 'mistral',
    'azure-anthropic', 'azure-openai', 'deepseek', 'zai',
]
VSCODE_PROVIDERS = [
    'ollama', 'llamacpp', 'openai', 'anthropic', 'groq', 'deepseek', 'zai',
    'google',
]
KNOWN_PROVIDERS = set(DEVTEAM_PROVIDERS) | set(VSCODE_PROVIDERS)

GENERATED_NOTE = 'GENERATED by my-dev-team-config/scripts/sync_models.py - edit models.yaml there, not this file.'


def fail(message: str) -> None:
    raise SystemExit(f'models.yaml invalid: {message}')


def load_registry(path: Path) -> dict:
    registry = yaml.safe_load(path.read_text(encoding='utf-8'))
    validate(registry)
    return registry


def validate(registry: dict) -> None:
    models = registry.get('models') or []
    if not models:
        fail('no models defined')
    seen_ids = set()
    for entry in models:
        model_id = entry.get('id')
        if not model_id:
            fail(f'entry without id: {entry}')
        if model_id in seen_ids:
            fail(f'duplicate id {model_id!r}')
        seen_ids.add(model_id)
        for field in ('label', 'provider', 'model', 'capabilities', 'complexity_fit', 'notes'):
            if not entry.get(field):
                fail(f'{model_id}: missing {field!r}')
        if entry['provider'] not in KNOWN_PROVIDERS:
            fail(f'{model_id}: unknown provider {entry["provider"]!r}')
        for extra in entry.get('also_via', []):
            if extra not in KNOWN_PROVIDERS:
                fail(f'{model_id}: unknown also_via provider {extra!r}')
        for name, score in entry['capabilities'].items():
            if name not in UNIFIED_CAPABILITIES:
                fail(f'{model_id}: unknown capability {name!r}')
            if not 0 <= score <= 1:
                fail(f'{model_id}: capability {name} out of [0, 1]')
        fit = entry['complexity_fit']
        if sorted(fit) != sorted(COMPLEXITY_LEVELS):
            fail(f'{model_id}: complexity_fit must have exactly low/medium/high')
        top = max(fit.values())
        if sum(1 for value in fit.values() if value == top) != 1:
            fail(f'{model_id}: complexity_fit needs a unique maximum to derive the vs-code tier')
        if 'thinking' in entry and entry['provider'] != 'ollama':
            fail(f'{model_id}: thinking is an Ollama-only field')
    for compound, spec in (registry.get('compound_providers') or {}).items():
        for member in spec.get('members', []):
            if member not in seen_ids:
                fail(f'compound provider {compound!r}: unknown member {member!r}')


def fmt_num(value) -> str:
    """YAML scalar for a score: ints stay ints (speed: 1), floats keep the dot."""
    return repr(value) if isinstance(value, float) else str(value)


def tier_of(entry: dict) -> str:
    fit = entry['complexity_fit']
    return TIER_BY_LEVEL[max(fit, key=fit.get)]


# --------------------------------------------------------------- my-dev-team

def emit_model_block(entry: dict, indent: str, provider_field: str | None) -> list[str]:
    lines = [f"{indent}- id: '{entry['model']}'"]
    field = indent + '  '
    if provider_field:
        lines.append(f'{field}provider: {provider_field}')
    if entry['provider'] == 'ollama':
        lines.append(f'{field}thinking: {str(entry.get("thinking", True)).lower()}')
    if 'context_window' in entry:
        lines.append(f'{field}context_window: {entry["context_window"]}')
    lines.append(f'{field}capabilities:')
    for name in UNIFIED_CAPABILITIES:
        if name in entry['capabilities']:
            lines.append(f'{field}    {name}: {fmt_num(entry["capabilities"][name])}')
    fit = entry['complexity_fit']
    fit_body = ', '.join(f'{level}: {fmt_num(fit[level])}' for level in COMPLEXITY_LEVELS)
    lines.append(f'{field}complexity_fit: {{{fit_body}}}')
    return lines


def emit_llms_yaml(registry: dict) -> str:
    models = registry['models']
    lines = [
        '# GENERATED FILE - do not edit by hand.',
        '# Source of truth: my-dev-team-config/models.yaml (the shared model registry).',
        '# Regenerate with: python scripts/sync_models.py (run in my-dev-team-config).',
        'providers:',
    ]
    for provider in DEVTEAM_PROVIDERS:
        section = [
            entry for entry in models
            if entry['provider'] == provider or provider in entry.get('also_via', [])
        ]
        if not section:
            continue
        lines.append(f'    {provider}:')
        lines.append('        models:')
        for entry in section:
            lines.extend(emit_model_block(entry, ' ' * 12, provider_field=None))
    by_id = {entry['id']: entry for entry in models}
    for compound, spec in (registry.get('compound_providers') or {}).items():
        lines.append(f'    {compound}:  # {spec["description"]}')
        lines.append('        models:')
        for member in spec['members']:
            entry = by_id[member]
            lines.extend(emit_model_block(entry, ' ' * 12, provider_field=entry['provider']))
    aliases = registry.get('aliases') or {}
    if aliases:
        lines.append('')
        lines.append('aliases:')
        for source, target in aliases.items():
            lines.append(f"    '{source}': '{target}'")
    return '\n'.join(lines) + '\n'


# ---------------------------------------------------------------------- vs-code

def fmt_context_window(value: int) -> str:
    return f'{value:_}' if value >= 1000 else str(value)


def emit_vscode_model(entry: dict) -> str:
    lines = [
        '---',
        f'# {GENERATED_NOTE}',
        f'id: {entry["id"]}',
        f'label: {entry["label"]}',
        f'provider: {entry["provider"]}',
        f'model: {entry["model"]}',
    ]
    if 'context_window' in entry:
        lines.append(f'contextWindow: {fmt_context_window(entry["context_window"])}')
    lines.append(f'tier: {tier_of(entry)}')
    if entry.get('triage_only'):
        lines.append('triageOnly: true')
    lines.append('capabilities:')
    for name in UNIFIED_CAPABILITIES:
        if name in entry['capabilities']:
            lines.append(f'  {name}: {fmt_num(entry["capabilities"][name])}')
    lines.append('---')
    lines.append('')
    lines.append(entry['notes'].rstrip('\n'))
    return '\n'.join(lines) + '\n'


def emit_vscode_models(registry: dict) -> dict[str, str]:
    return {
        f'{entry["id"]}.md': emit_vscode_model(entry)
        for entry in registry['models']
        if entry['provider'] in VSCODE_PROVIDERS
    }


# ----------------------------------------------------------------------- sync

def sync_file(path: Path, content: str, check: bool) -> str:
    current = path.read_text(encoding='utf-8') if path.exists() else None
    if current == content:
        return 'unchanged'
    if not check:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding='utf-8', newline='\n')
    return 'created' if current is None else 'updated'


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--devteam', type=Path, default=REPO_ROOT.parent / 'my-dev-team',
                        help='path to the my-dev-team checkout (default: sibling)')
    parser.add_argument('--vscode', type=Path, default=REPO_ROOT.parent / 'my-dev-team-vs-code',
                        help='path to the my-dev-team-vs-code checkout (default: sibling)')
    parser.add_argument('--check', action='store_true',
                        help='write nothing; exit 1 when a generated file would change')
    args = parser.parse_args()

    registry = load_registry(REPO_ROOT / 'models.yaml')
    drift = False

    llms_path = args.devteam / 'src' / 'devteam' / 'config' / 'tools' / 'llms.yaml'
    state = sync_file(llms_path, emit_llms_yaml(registry), args.check)
    drift |= state != 'unchanged'
    print(f'{state:>9}  {llms_path}')

    models_dir = args.vscode / 'src' / 'engine' / 'config' / 'models'
    files = emit_vscode_models(registry)
    for name, content in sorted(files.items()):
        state = sync_file(models_dir / name, content, args.check)
        drift |= state != 'unchanged'
        print(f'{state:>9}  {models_dir / name}')
    for stale in sorted(models_dir.glob('*.md')):
        if stale.name not in files:
            drift = True
            if not args.check:
                stale.unlink()
            print(f'{"deleted":>9}  {stale}')

    if args.check and drift:
        print('\ndrift detected: run python scripts/sync_models.py to regenerate')
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
